# Generated by Django 3.0.6 on 2020-06-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hojadevida', '0003_auto_20200603_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['created']},
        ),
    ]
